name: Build and test

on:
  pull_request:
    branches: [ master, main ]
  push:
    branches: [ master, main ]

jobs:
  build-and-test:
    uses: GTNewHorizons/GTNH-Actions-Workflows/.github/workflows/build-and-test.yml@master
    secrets: inherit
#    with:
#      timeout: 150
#      workspace: setupDecompWorkspace
#      client-only: false
#      disable-server-auto-stop: false
#      horizonqa: true
#      horizonqa-tests: ''
#      horizonqa-allow-no-tests: false
#      external-deps-inclusion: true
